# This is a basic workflow to help you get started with Actions

name: My-Github_Actions
on:
  push:
    branches: [ main ]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: run-lint
      run: make lint
